# Generated by Django 4.2.4 on 2023-08-31 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('item_name', models.TextField()),
                ('base_quantity', models.IntegerField()),
                ('new_unit_price', models.IntegerField()),
                ('type', models.TextField()),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.TextField()),
                ('item_name', models.TextField()),
                ('base_quantity', models.IntegerField()),
                ('group_cost', models.IntegerField()),
                ('type', models.TextField()),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felso_app.components')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felso_app.groups')),
            ],
        ),
    ]
